# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example' do
  pod 'RNAdyenCse', :podspec => '../node_modules/react-native-adyen-cse/ios/RNAdyenCse.podspec'
end

